# Generated by Django 5.2.17 on 2026-09-15 19:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e164', models.CharField(help_text='Normalized international format, e.g. +15125551234.', max_length=16, unique=True)),
                ('national_format', models.CharField(blank=True, help_text='National display format, e.g. (512) 555-1234.', max_length=32)),
                ('raw_phone', models.CharField(blank=True, help_text='Original phone text as received from the source.', max_length=64)),
                ('area_code', models.CharField(blank=True, db_index=True, max_length=3)),
                ('state', models.CharField(blank=True, db_index=True, max_length=2)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=512)),
                ('city', models.CharField(blank=True, db_index=True, max_length=128)),
                ('postal_code', models.CharField(blank=True, max_length=16)),
                ('category', models.CharField(blank=True, max_length=128)),
                ('source_record_id', models.CharField(blank=True, help_text='Provider-specific place/POI id when available.', max_length=128)),
                ('source_url', models.URLField(blank=True, max_length=1024)),
                ('source_query', models.CharField(blank=True, help_text='Query or page that produced this record.', max_length=512)),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Original source payload for audit.')),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending'), ('valid', 'Valid'), ('invalid', 'Invalid')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phone_records', to='sources.datasource')),
            ],
            options={
                'verbose_name': 'phone record',
                'verbose_name_plural': 'phone records',
                'ordering': ['-last_seen_at', 'e164'],
                'indexes': [models.Index(fields=['e164'], name='phones_e164_idx'), models.Index(fields=['area_code', 'state'], name='phones_area_state_idx'), models.Index(fields=['source', 'last_seen_at'], name='phones_source_seen_idx')],
            },
        ),
    ]
