# Generated by Django 5.2.17 on 2026-09-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonerecord',
            name='carrier',
            field=models.CharField(blank=True, help_text='Often empty for US NANP from DialCode.', max_length=128),
        ),
        migrations.AddField(
            model_name='phonerecord',
            name='enriched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phonerecord',
            name='enrichment_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='phonerecord',
            name='enrichment_geo',
            field=models.CharField(blank=True, help_text='Confirmed geography hints (area name, timezone).', max_length=255),
        ),
        migrations.AddField(
            model_name='phonerecord',
            name='enrichment_raw',
            field=models.JSONField(blank=True, default=dict, help_text='DialCode (or other) enrichment payload for audit.'),
        ),
        migrations.AddField(
            model_name='phonerecord',
            name='enrichment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('offline_only', 'Offline only'), ('enriched', 'Enriched'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='phonerecord',
            name='line_type',
            field=models.CharField(blank=True, help_text='e.g. mobile, fixed_line, toll_free, voip, unknown.', max_length=32),
        ),
        migrations.AddField(
            model_name='phonerecord',
            name='risk_level',
            field=models.CharField(blank=True, help_text='Mapped from DialCode risk.scam_risk.', max_length=32),
        ),
        migrations.AddField(
            model_name='phonerecord',
            name='risk_signals',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
