# Generated by Django 5.2.17 on 2026-09-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('source_type', models.CharField(choices=[('api', 'API'), ('website', 'Website')], default='api', max_length=16)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower number = higher priority when scheduling.')),
                ('is_active', models.BooleanField(default=True)),
                ('api_key_env_var', models.CharField(blank=True, help_text='Environment variable name that holds the API key (e.g. YELP_API_KEY).', max_length=128)),
                ('credential_notes', models.TextField(blank=True, help_text='How credentials are obtained; never store raw secrets here.')),
                ('quota_max', models.PositiveIntegerField(blank=True, help_text='Max free calls/units in the current window. Null for soft-only sources.', null=True)),
                ('quota_remaining', models.PositiveIntegerField(blank=True, help_text='Remaining free calls/units after safety buffer accounting.', null=True)),
                ('window_type', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('per_sku', 'Per SKU'), ('soft', 'Soft (politeness limits)')], default='daily', max_length=16)),
                ('quota_reset_at', models.DateTimeField(blank=True, help_text='When the current quota window resets.', null=True)),
                ('quota_refreshed_at', models.DateTimeField(blank=True, help_text='Last time quota counters were refreshed from headers or calculation.', null=True)),
                ('safety_buffer_percent', models.PositiveSmallIntegerField(default=10, help_text='Percent of quota_max left untouched (typically 5–10).')),
                ('quota_status', models.CharField(choices=[('healthy', 'Healthy'), ('low', 'Low'), ('exhausted', 'Exhausted'), ('error', 'Error')], default='healthy', max_length=16)),
                ('last_successful_run_at', models.DateTimeField(blank=True, null=True)),
                ('allowed_params', models.JSONField(blank=True, default=dict, help_text='Allowed query parameters (cities, categories, radius, pagination).')),
                ('data_quality_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'data source',
                'verbose_name_plural': 'data sources',
                'ordering': ['priority', 'name'],
            },
        ),
    ]
