# Generated by Django 5.2.17 on 2026-09-16 08:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrchestrationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_id', models.PositiveSmallIntegerField(default=1, unique=True)),
                ('city_index', models.PositiveIntegerField(default=0)),
                ('category_index', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'orchestration state',
                'verbose_name_plural': 'orchestration state',
            },
        ),
        migrations.CreateModel(
            name='HarvestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=128)),
                ('category', models.CharField(blank=True, max_length=128)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('skipped', 'Skipped'), ('failed', 'Failed')], db_index=True, default='success', max_length=16)),
                ('fetched', models.PositiveIntegerField(default=0)),
                ('saved', models.PositiveIntegerField(default=0)),
                ('updated', models.PositiveIntegerField(default=0)),
                ('skipped_invalid', models.PositiveIntegerField(default=0)),
                ('quota_remaining_before', models.PositiveIntegerField(blank=True, null=True)),
                ('quota_remaining_after', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('cursor_before', models.JSONField(blank=True, default=dict)),
                ('cursor_after', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvest_runs', to='sources.datasource')),
            ],
            options={
                'verbose_name': 'harvest run',
                'verbose_name_plural': 'harvest runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AcquisitionCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=128)),
                ('cursor_payload', models.JSONField(blank=True, default=dict, help_text='e.g. {"offset": 50} or {"page_token": "..."}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acquisition_cursors', to='sources.datasource')),
            ],
            options={
                'verbose_name': 'acquisition cursor',
                'verbose_name_plural': 'acquisition cursors',
                'constraints': [models.UniqueConstraint(fields=('source', 'city', 'category'), name='acquisition_cursor_source_city_category_uniq')],
            },
        ),
    ]
