# Generated by Django 5.2.17 on 2026-09-16 12:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acquisition', '0001_orchestration'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcquisitionDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('category', models.CharField(blank=True, max_length=128)),
                ('outcome', models.CharField(choices=[('selected', 'Selected'), ('skipped_cycle', 'Skipped cycle'), ('ran', 'Ran'), ('failed', 'Failed')], db_index=True, max_length=16)),
                ('skipped', models.JSONField(blank=True, default=list, help_text='List of {"slug": "...", "reason": "..."} for ineligible sources.')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'acquisition decision',
                'verbose_name_plural': 'acquisition decisions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='harvestrun',
            index=models.Index(fields=['started_at', 'status'], name='harvest_started_status_idx'),
        ),
        migrations.AddField(
            model_name='acquisitiondecision',
            name='chosen_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquisition_decisions', to='sources.datasource'),
        ),
        migrations.AddField(
            model_name='acquisitiondecision',
            name='harvest_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='acquisition.harvestrun'),
        ),
    ]
